# Generated by Django 2.2.1 on 2019-05-03 12:17

import destination.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(null=True, upload_to=destination.models.hotel_feature_image_name, verbose_name='Featured Image - 100px x 100 px'),
        ),
    ]
